<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(null, array('page' => $this->previous)); ?>">
        « Предыдущая</a>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url(null, array('page' => $page)); ?>">
            <?php echo $page; ?></a>
        <?php else: ?>
        <?php echo $page; ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(null, array('page' => $this->next)); ?>">
        Следующая »</a>
    <?php endif; ?>
    (1-<?php echo $this->itemCountPerPage ?>/<?php echo $this->totalItemCount ?>) |
    На страницу: <?php if ($this->itemCountPerPage == 25) { ?>25<?php } else { ?><a href="<?php echo $this->url(null, array('per-page' => 25)); ?>">25</a><?php } ?>,
    <?php if ($this->itemCountPerPage == 50) { ?>50<?php } else { ?><a href="<?php echo $this->url(null, array('per-page' => 50)); ?>">50</a><?php } ?>,
    <?php if ($this->itemCountPerPage == 100) { ?>100<?php } else { ?><a href="<?php echo $this->url(null, array('per-page' => 100)); ?>">100</a><?php } ?>
</div>
<?php endif; ?>