<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(null, array('page' => $this->previous)); ?>">
        « Предыдущая</a>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url(null, array('page' => $page)); ?>">
            <?php echo $page; ?></a>
        <?php else: ?>
        <?php echo $page; ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(null, array('page' => $this->next)); ?>">
        Следующая »</a>
    <?php endif; ?>
    (1-25/<?php echo $this->totalItemCount ?>) |  На страницу: 25, <a href="#">50</a>, <a href="#">100</a>
</div>
<?php endif; ?>