<h3 style="width: 300px; float: left;"><img style="width: 20px;" src="#" alt="Мои задачи" title="Мои задачи">Мои задачи (123)</h3>
<h3 style="width: 350px; float: left;"><img style="width: 20px;" src="#" alt="Мое время" title="Мое время">Мое время (00:00:00)</h3>
<h3 style="float: right;"><img src="/img/office.png" alt="Офис" title="Офис"> 00:00:00 <img style="width: 20px;" src="#" alt="Старт" title="Старт"><img style="width: 20px;" src="#" alt="Стоп" title="Стоп"></h3>
<table cellspacing="0" cellpadding="0" class="table table-bordered">
    <thead>
    <tr>
      <th>#</th>
      <th>Трекер</th>
      <th style="width: 162px;">Время</th>
      <th>Тема</th>
      <th>Версия</th>
      <th>Даты</th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($paginator)): ?>
    <?php foreach ($paginator as $item): ?>
     <?php $issue = new \Application\Model\IssueModel(); $issue->exchangeArray($item); ?>
    <tr class="priority-<?php echo $issue->getPriorityId() ?>">
        <td><a target="_blank" href="http://redmine.f-technology.ru/issues/<?php echo $issue->getId() ?>"><?php echo $issue->getId() ?></a></td>
        <td><?php echo $issue->getTracker() ?></td>
        <td><div style="width: 162px;">000:00:00 / <a class="issue-estimation" href="/issues/estimate/"><b>100:00:00</b></a>
            <a issieId="<?php echo $issue->getId() ?>" href="/issues/start/<?php echo $issue->getId() ?>/"><img class="issue-time-show" src="/img/play.png" alt="В работу" title="В работу"></a><?php
            ?><a issieId="<?php echo $issue->getId() ?>" href="/issues/pause/<?php echo $issue->getId() ?>"><img class="issue-time-hide" src="/img/pause.png" alt="Отложить" title="Отложить"></a><?php
            ?><a issieId="<?php echo $issue->getId() ?>" href="/issues/stop/<?php echo $issue->getId() ?>"><img class="issue-time-show" src="/img/stop.png" alt="Выполнено" title="Выполнено"></a></div>
            <table title="<?php echo $issue->getDoneRatio() ?>%" class="progress" style="width: 162px; margin-top: 4px"><tbody><tr><td class="closed" style="width: <?php echo $issue->getDoneRatio() ?>%;"></td><td class="todo" style="width: <?php echo 100 - $issue->getDoneRatio() ?>%;"></td></tr></tbody></table><p class="pourcent"></p>
        </td>
        <td><a target="_blank" href="http://redmine.f-technology.ru/issues/<?php echo $issue->getId() ?>">Фабрикант » ЭТП » ® Фабрикант » Разработка</a><br/><b><a target="_blank" href="http://redmine.f-technology.ru/issues/<?php echo $issue->getId() ?>"><?php echo $issue->getSubject() ?></a></b></td>
        <td><a href="#">r-187</a><br/><nobr><b><a href="http://analytic-56123.fabrikant.test">analytic-56123</a></b></nobr></td>
        <td>
            <div style="float: left; margin-left: 6px; padding-right: 5px;">с</div> <?php echo $issue->getDueDate() != '' ? date('d.m.Y', strtotime($issue->getDueDate())) : '' ?></br>
            до <b><?php echo $issue->getDueDate() != '' ? date('d.m.Y', strtotime($issue->getDueDate())) : '' ?></b>
        </td>
    </tr>
        <?php endforeach; ?>
    <?php else: ?>
    <td colspan="<?php echo count($headers) + 1 ?>"><?php echo $this->translate('Задачи отсутствуют') ?></td>
    <?php endif; ?>
</table>
<?php echo $this->paginationControl($paginator, 'sliding', 'pagination') ?>
    </tbody>
</table>